version: "3"
#all containers
services:
# container_name
  docker_compose_app: 
  # dockerfile
    build: .
    ports:
    - "3030:3030"
    volumes:
    - .:/flask
    depends_on:
    - redis
  redis:
    image: redis:6.2.6